name: Docker

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ new-commit-from-SVF ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     -
        name: Checkout 
        uses: actions/checkout@v2
     -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWD}}
     -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USER}}/teaching-software-analysis:latest
